[package]
name = "darkfi"
version = "0.1.0"
homepage = "https://dark.fi"
description = "Anonymous. Uncensored. Sovereign."
authors = ["darkfi <dev@dark.fi>"]
repository = "https://github.com/darkrenaissance/darkfi"
readme = "README.md"
license = "AGPL-3.0-only"
edition = "2018"

#[profile.release]
#debug = 1

[lib]
name = "drk"

[dependencies]
ff = "0.8"
group = "0.8"
bellman = { version = "0.8", default-features = false, features = ["groth16"] }
bls12_381 = "0.3.1"
jubjub = "0.5.1"
zcash_primitives = "0.5.0"
zcash_proofs = "0.5.0"
rand = "0.7.3"
rand_core = "0.5.1"
sha2 = "0.9.8"
blake2s_simd = "0.5"
blake2b_simd = "0.5.11"
crypto_api_chachapoly = "0.4"
bitvec = "0.18"
bimap = "0.5.2"
hex = "0.4.2"
bs58 = "0.4.0"
prettytable-rs = "0.8"
num_cpus = "1.13.0"

smol = "1.2.4"
futures = "0.3.17"
async-channel = "1.4.2"
async-trait = "0.1.42"
async-executor = "1.4.0"
async-std = "1.6.2"
async-native-tls = "0.3.3"
native-tls = "0.2.8"
easy-parallel = "3.1.0"

tungstenite = "0.15.0"
async-tungstenite = "0.15.0"

simple_logger = "1.13.0"
log = "0.4.14"
clap = "2.33.3"
toml = "0.5.8"
dirs = "4.0.0"
url = "2.2.2"
serde = { version = "1.0.126", features = ["derive"]}
serde_json = "1.0.61"
bytes = "1.0.1"
signal-hook = "0.3.8"
lazy_static = "1.4.0"

rocksdb = {version = "0.16.0", default-features = false, features = ["lz4"]}

## Cashier Solana Dependencies
spl-token = {version = "3.2.0", optional = true}
solana-sdk = {version = "1.7.11", optional = true}
solana-client = {version = "1.7.11", optional = true}
spl-associated-token-account = {version = "1.0.3", optional = true}

## Cashier Bitcoin Dependencies
bitcoin = {version = "0.27.0", optional = true }
bitcoin_hashes = "0.10.0"
secp256k1 = {version = "0.20.3", default-features = false, features = ["rand-std"], optional = true}
electrum-client = {version = "0.8.0", optional = true }

[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled", "sqlcipher"]

[dependencies.zeromq]
git = "https://github.com/zeromq/zmq.rs"
default-features = false
features = ["async-std-runtime", "all-transport"]

[features]
btc = ["bitcoin", "secp256k1", "electrum-client"]
sol = ["solana-sdk", "solana-client", "spl-token", "spl-associated-token-account"]
